openapi: 3.0.0
info:
  title: Simple Inventory API
  description: This is a simple API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0-oas3
servers:
  - url: 'https://virtserver.swaggerhub.com/solo295/test/1.0.0'
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /api/workspace:
    post:
      summary: create new workspace
      description: Create new workspace
      operationId: creaateWorkspace
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    description: workspace url
          description: success response
        default:
          description: Default error sample response
      parameters:
        - name: userID
          in: query
          description: user id
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: name
          in: query
          description: workspace name
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: channelName
          in: query
          description: Channel name created by default
          required: false
          style: form
          explode: true
          schema:
            type: string
    get:
      summary: select user workspace
      description: select user workspace
      operationId: ''
      parameters:
        - name: oauthId
          in: query
          description: user id
          required: true
          explode: true
          schema:
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  workspaces:
                    type: array
                    items:
                      type: object
                      properties:
                        workspaceID:
                          type: integer
                        workspaceName:
                          type: string
                        workspaceURL:
                          type: string
                    description: invite url
          description: success response
        default:
          description: Default error sample response
  /api/workspace/invite:
    summary: invite to workspace
    description: invite to workspace
    post:
      summary: invite to workspace
      description: invite to workspace
      operationId: ''
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    description: invite url
          description: success response
        default:
          description: Default error sample response
      parameters:
        - name: workspaceID
          in: query
          description: workspace id
          required: true
          style: form
          explode: true
          schema:
            type: integer
        - name: userID
          in: query
          description: user id
          required: true
          style: form
          explode: true
          schema:
            type: string
  /api/user/sign-in/github:
    summary: workspace user login
    description: selectworkspace user login
    post:
      summary: workspace user login
      description: workspace user login
      operationId: ''
      parameters:
        - name: oauthId
          in: query
          description: workspace user id
          required: true
          explode: true
          schema:
            type: integer
      responses:
        '200':
          description: signin success
        '400':
          description: bad input parameter
  /api/user/sign-out:
    summary: workspace user signout
    description: selectworkspace user signout
    delete:
      summary: workspace user signout
      description: workspace user signout
      operationId: ''
      parameters:
        - name: workspaceUserInfoId
          in: query
          description: workspace user id
          required: true
          explode: true
          schema:
            type: integer
      responses:
        '200':
          description: search results matching criteria
        '400':
          description: bad input parameter
